# Generated by Django 3.1.7 on 2021-03-29 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='description',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='data',
            name='exercise',
            field=models.CharField(default=None, max_length=25),
        ),
    ]
