# Generated by Django 3.1.7 on 2021-03-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210329_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='exercise_name',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AlterField(
            model_name='data',
            name='exercise',
            field=models.CharField(max_length=10),
        ),
    ]
